language: node_js

node_js:
  - '12.7'

addons:
  chrome: stable

env:
  - TRAVIS=true

script:
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng e2e --protractor-config=./e2e/protractor-ci.conf.js

